### ISSUE TITLE
Bug: `double` output display does not look right

### ISSUE THREAD

**Issue by TonyWu20** [TonyWu20/chemrust#7]
The generated model does not have bonds with the target bondlength.

Parameters to reproduce the bug:

```yaml
mount_scanner_version: `main` branch
model_path: ./scanner_test_models/Fe.cell
new_element: O
target_bondlength: 2.1
x_range: [0.38, 0.79]
y_range: [0.28, 0.64]
z_range: [0.48, 0.53]
export_dir: ./demo/O_2.1_Fe_BP_ranged
kpoint_quality: Coarse
edft: false
```
